### ISSUE TITLE
为啥图标预览方形的那块，点击了自动跳转一整张图，没有跳转到单个的

### ISSUE THREAD

**Issue by javazwz123** [xushier/HD-Icons#100]
https://raw.githubusercontent.com/xushier/HD-Icons/main/_icons-radius.png
这个地址，下面圆形的其他的都是正常的

**Comment by xushier** [comment]
因为单图的话，图太多了，一是加载慢，二是会被github认为是图床封禁，所以合并为一张了。需要看可以到这里
https://cdn.jsdelivr.net/gh/xushier/HD-Icons/

**Comment by javazwz123** [comment]
> 因为单图的话，图太多了，一是加载慢，二是会被github认为是图床封禁，所以合并为一张了。需要看可以到这里 https://cdn.jsdelivr.net/gh/xushier/HD-Icons/

哦哦哦，谢谢谢谢

**Comment by xushier** [comment]
> > 因为单图的话，图太多了，一是加载慢，二是会被github认为是图床封禁，所以合并为一张了。需要看可以到这里 https://cdn.jsdelivr.net/gh/xushier/HD-Icons/
> 
> 不过这个地址也是要一个个点，有个建议是可以把每个LOGO缩略图下都有个对应的名字，有些LOGO感觉是可以通用的，特别好看，一个个点进去看太浪费时间了

嗯，后面看可以的话改一下

**Comment by xushier** [comment]
> > 因为单图的话，图太多了，一是加载慢，二是会被github认为是图床封禁，所以合并为一张了。需要看可以到这里 https://cdn.jsdelivr.net/gh/xushier/HD-Icons/
> 
> 不过这个地址也是要一个个点，有个建议是可以把每个LOGO缩略图下都有个对应的名字，有些LOGO感觉是可以通用的，特别好看，一个个点进去看太浪费时间了

已添加文字说明
