### ISSUE TITLE
请求新增几枚图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#101]
## 你想要新增什么图标？

smartdns、IPTV、mosdns、sftpgo

## 该图标有可参考的项目或 LOGO 地址吗？
smartdns：
![Smart-DNS-for-beginners-1](https://github.com/xushier/HD-Icons/assets/52785574/bf4be605-00be-4bcd-8ecb-ed5bb05fb425)

![CD---What-is-SmartDNS-blog-header-v2](https://github.com/xushier/HD-Icons/assets/52785574/ecc2f46a-3839-4401-9349-232b4c80ee3b)
![smartdns-banner](https://github.com/xushier/HD-Icons/assets/52785574/c4a7179a-d1ce-43e3-8405-dc2be98cbd6b)

IPTV：
![iptv png55](https://github.com/xushier/HD-Icons/assets/52785574/dccc7045-e541-4324-9845-dfed6c93a217)
![iptv](https://github.com/xushier/HD-Icons/assets/52785574/7755057a-c208-4e5c-8aa5-73194b786eaf)
![1200x1200bb](https://github.com/xushier/HD-Icons/assets/52785574/2da3e1fa-29e6-47aa-b41e-e471dec96d87)
![13576-](https://github.com/xushier/HD-Icons/assets/52785574/96c93465-d721-48c6-82df-b41a9fc111ff)
![iptv](https://github.com/xushier/HD-Icons/assets/52785574/148dce7a-e22a-4728-8334-f467c7232f1c)

mosdns：
![68747470733a2f2f747275656368617274732e6f72672f696d672f686f746c696e6b2d6f6b2f63686172742d69636f6e732f6d6f73646e732e706e67](https://github.com/xushier/HD-Icons/assets/52785574/5385d220-b7ae-4297-8b00-dcaafef10c1c)

sftpgo：
![SFTPgo-logo](https://github.com/xushier/HD-Icons/assets/52785574/d8876efe-0186-4200-8986-3e37d30ea088)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/e9876865255cc7ed09e45a93e7b0626a9d726275
