### ISSUE TITLE
请求新增一枚tvhelper图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#102]
## 你想要新增什么图标？

tvhelper

## 该图标有可参考的项目或 LOGO 地址吗？
![R](https://github.com/xushier/HD-Icons/assets/52785574/72315916-b4ce-46e6-ab23-64311bd1a838)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/e9876865255cc7ed09e45a93e7b0626a9d726275
