### ISSUE TITLE
请求增加music-tag-web图标

### ISSUE THREAD

**Issue by ChenXu178** [xushier/HD-Icons#103]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
music-tag-web 一个刮削音乐文件的项目

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
https://github.com/xhongc/music-tag-web
https://github.com/xhongc/music-tag-web/blob/dev_1.0/web/static/img/music_null-cutout.png

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> > music-tag-web 一个刮削音乐文件的项目
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。
> > https://github.com/xhongc/music-tag-web
> > https://github.com/xhongc/music-tag-web/blob/dev_1.0/web/static/img/music_null-cutout.png

这个是有的，https://cdn.jsdelivr.net/gh/xushier/HD-Icons/border-radius/Musictag_A.png
