### ISSUE TITLE
请求添加jumpserver

### ISSUE THREAD

**Issue by BilikoX** [xushier/HD-Icons#108]
![logo](https://raw.githubusercontent.com/jumpserver/jumpserver/dev/apps/static/img/logo.png)

[https://github.com/jumpserver/jumpserver](https://github.com/jumpserver/jumpserver)

[官网](https://www.jumpserver.org/)

[DockerHub](https://hub.docker.com/r/jumpserver/jms_all)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/104446552d8058e37a44fd13796284939de5302c
