### ISSUE TITLE
请求添加 Homebridge

### ISSUE THREAD

**Issue by ariakeumi** [xushier/HD-Icons#109]
## 你想要新增什么图标？

Homebridge

## 该图标有可参考的项目或 LOGO 地址吗？

https://github.com/homebridge/homebridge

![homebridge-color-round-stylized](https://github.com/xushier/HD-Icons/assets/13041855/a08a0d5e-7bc6-4a01-be95-6ed7b94ed77c)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/104446552d8058e37a44fd13796284939de5302c
