### ISSUE TITLE
请求添加Nessus

### ISSUE THREAD

**Issue by BilikoX** [xushier/HD-Icons#110]
这两个logo都可以
![7b44a4b9b6845236b28cfc66de2f95a7](https://github.com/xushier/HD-Icons/assets/15882517/dee5dcb6-a21e-4162-857a-a7596e0f1b80)
![TenableLogo_FullColor_RGB](https://github.com/xushier/HD-Icons/assets/15882517/30eeb26d-4d8f-4566-a324-0c5709143a69)
[SVG](https://[static.tenable.com/press/logos/TenableLogo_FullColor_RGB.svg](https://static.tenable.com/press/logos/TenableLogo_FullColor_RGB.svg))

[Docker Hub](https://hub.docker.com/r/tenable/nessus)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/104446552d8058e37a44fd13796284939de5302c
