### ISSUE TITLE
请求添加 next-terminal

### ISSUE THREAD

**Issue by Tarocch1** [xushier/HD-Icons#112]
## 你想要新增什么图标？

> next-terminal

## 该图标有可参考的项目或 LOGO 地址吗？

> https://github.com/dushixiang/next-terminal
> https://next-terminal.typesafe.cn/assets/images/favicon.ico

![favicon](https://github.com/xushier/HD-Icons/assets/15124068/1f2a07e8-6d34-4b28-bdf8-0aecc4ddcb90)

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
