### ISSUE TITLE
请求新增两枚图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#113]
## 你想要新增什么图标？

dae、 clash-verge

## 该图标有可参考的项目或 LOGO 地址吗？

![logo](https://github.com/xushier/HD-Icons/assets/52785574/2ef6ec30-a43f-4ad2-9935-935ac2056572)
![logo1](https://github.com/xushier/HD-Icons/assets/52785574/d5cfa095-b579-4c00-bf8d-396ce712a591)

**Comment by sepshow** [comment]
> 大鹅这个图貌似是 Steam 游戏 《大鹅模拟器》里的？

https://github.com/daeuniverse/dae 这个项目

**Comment by xushier** [comment]
嗯，我记得大鹅项目原本没图的

**Comment by sepshow** [comment]
> 嗯，我记得大鹅项目原本没图的
小迪老师 发现一枚新的大鹅图标

![下载](https://github.com/xushier/HD-Icons/assets/52785574/64dc1830-1404-49ba-9844-eff85d7e1ab8)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/1ed01d380309cca4800350f4c1b19d8a26ac7d19
