### ISSUE TITLE
请求添加几个图标

### ISSUE THREAD

**Issue by x2287711259** [xushier/HD-Icons#114]
## 你想要新增什么图标？

1.开源交互审计系统next-terminal
2.音乐项目musicn
3.TeraBox图标更改了
4.中国移动云盘

## 该图标有可参考的项目或 LOGO 地址吗？

1.https://next-terminal.typesafe.cn/
2.https://github.com/zonemeen/musicn/blob/main/public/music.png
3.https://www.terabox.com/
4.https://yun.139.com/

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
