### ISSUE TITLE
请更新AutoSymlink的图标

### ISSUE THREAD

**Issue by shenxianmq** [xushier/HD-Icons#116]
## 你想要新增什么图标？

目前的图标加了一层蒙版，看起来太暗了

希望变成这样的
![AutoSymlink](https://github.com/xushier/HD-Icons/assets/76782947/a7d3b6f1-78a1-46d5-b59e-d21f1ed3c517)
![image](https://github.com/xushier/HD-Icons/assets/76782947/62fe053c-12de-4f2f-9561-e561f14c296b)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/1ed01d380309cca4800350f4c1b19d8a26ac7d19
