### ISSUE TITLE
请求图标

### ISSUE THREAD

**Issue by RaigonChen** [xushier/HD-Icons#117]
## 你想要新增什么图标？

> Memos

## 该图标有可参考的项目或 LOGO 地址吗？

> https://camo.githubusercontent.com/75302e03c8e45f10cb9f2c074f9bdf86e4846d4ac0b82dcc3ec3baa4145347c5/68747470733a2f2f7777772e7573656d656d6f732e636f6d2f66756c6c2d6c6f676f2d6c616e6473636170652e706e67

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/1ed01d380309cca4800350f4c1b19d8a26ac7d19
