### ISSUE TITLE
请求图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#118]
## 你想要新增什么图标？

sing-box 

## 该图标有可参考的项目或 LOGO 地址吗？

![icon](https://github.com/xushier/HD-Icons/assets/52785574/e9eda750-2378-4cd6-884a-0454d535b3a8)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/1ed01d380309cca4800350f4c1b19d8a26ac7d19
