### ISSUE TITLE
新增迅雷图标

### ISSUE THREAD

**Issue by aling466** [xushier/HD-Icons#119]
## 你想要新增什么图标？
迅雷（xunlei.png)
> 你想要新增什么图标？填写图标项目的完整名字。
Xunlei_B.png
##
![QX-迅雷](https://github.com/xushier/HD-Icons/assets/61304618/b1b8147b-3941-46d9-83cc-2b7a47dba121)
 该图标有可参考的项目或 LOGO 地址吗？
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAAAXNSR0IArs4c6QAADzBJREFUeF7tXUtW3UgSzRDUDgzn9KifV2KYGHvS9g4wK7G9EvAOoCYuMwFWYtWozjG1A4OynRJ66D1LT/lVRmZeJtV9nJ/IG3FfROQnRGKBv/df/1kJsb9qKvFKTUckjoSkVTe1fPrvAoJgigQRoLoVmmQtGllTJe7EI9WXbw9ul1gMhZpEkaKp9k87MoijUPNg3FIR6IgjhbyoGnEXijDeCfK/b/cfSdAHeIZSDTfWuqlWZPnz5OCzTwm8EGTtLYT45FM4jAUEzBHwSxRngnQeA8QwVyR6hEXAD1GsCaK8htzbP0d+EVbNGN0VAaqp+Xl8+fY/XbJv+GdFkPfXPz5ISeeGc6E5EIiEgL03MSbIu+v7G3iNSHrGtE4ISCE+mSbx2gRBSOWkG3RmgwDVVycvXuqKo0UQkEMXTrRLAwH9vESLIAir0lA7pDRBQM+TzBIE5DABHW3TQmCeJDsJAnKkpW5Ia4GAlBdXbw7PpnpOEgRbuRZgo0uSCOza3RolSJuUV/vfk1wthAYCxgiopF2ejV14HCUIQitjhNEheQTG85HfCILQKnlNYwGWCBDJs8vXhxfD7r8R5N23f7/jqrolwuiWOAK/e5ENguBmbuL6hfjuCGztam0QBN7DHV+MkDoCm15kTRDkHqkrFvL7QmCYi6wJAu/hC16Mkz4Cz15kQJD7X+cl+AMCQEAhQI04VuciLUEQXsEogMAmAv3peksQhFcwDyCwhQCJ26vXB8dPBEF4BQPhhgDVRE1bwifO8+4uDyGEV9wMo2R5urfjVfPwpS+yEDO6UXkI4XCwZIPksvbxogqx7wSqPITe/fXjXJCqhIg/ILAsAsoAh95iOPv7r/dHshI3y0q0NZuUFxSbpVEBwORRENhFjHZXlctzCxK3FDPGi6IdTBoNAd2yO3x+tKkGQaKZSykTmxVt47Vp1BIEW7ylmOqy6zQjBqvQagAUCLKs1RQxm24otQ0Gn9DqWTIQpAiTXWiRatdHPn62KRTNK7QCQRaymEKmUbs9jw9nNsTgGlr1moMHKcSGwyxzuhqIyXwcQysQxESDaLuFgHkCPgUh19AKBIHRWyFgm4CPTcbmQHAHEgixrMykxE5+wqkhcpxDK3iQEm3cas3+wqnh9NxDKxDEyljK6uQznNogB5e7VhrqRIilAVJ5TfyHU6mFVvAg5Vm91opDeY1+8hTyjiFQ8CBaZlNCo7BeQyGYGjmUzCBICbY/s8bQXiPlb1yCIEUTJLzXSJkc8CAFkyO011DQdgeBfzw9m5WrFOGGB0lRa04yh/cavXiqIEjViDtJ8jTVugcgiJOxJdZ55oOVoVaT8qM8ECSUVbAadzmvsb3sVE7Mp9QFgrAy5BDCKHL8PLZ9q+EqUepFQUAQVwtg3H+JRHzX8lP3HtjFYmzcbqLFC6mGcqd4MLiNOzyImyXy6/1UlTy2YDl4D3iQ2Fbkef7YIVVu3gME8WygMYfrv4gUU4Z+bhZ1dT0BgRDLE5DxhuGRb2x4j4wKooMg8SzbfWYm+cb2QlI+GESS7m6WLEbglG/k6j2Qg7AwdXMhOOUbOXsPEMTcNiP34Jdv5Ow9QJDI5m40PdN8o19Drl8qQ5JuZKWRGoMckYDHk9towOtOzDUZz91z9OuDB9G11AjtiOTZ5evDiwhTa02Za1g1XDwIomUKyzfivFOl0CiBHAUm6VQLknVr7pKe3khzeyvNe6fqN3KQuO2w5Iajnx+1zD1IV1dWvYu+fHtwOwWZKi4gxP5K7MmVbMSreO+nqb46efHSj2rDjKLemauRK5J/9+FfTifn26hlRhCqhWxuJVH958nBZxcTUaRpqv1TInEkpDhyGUurL/OdKrUGhcn2y8RcrrVP6SgDguh5CS0jnWjUlq+hvY/BPEsC5JjCL4dHUbtsIxGCUJc3kKylFG2oNBc2uRBiVyjWehUhPnkbP2Fy5HStPagHUXv1ymDXk+xtJmyNpP9OCaBi2Y1/e3wig3hoSRGr2MAuAqzDL1eiRCrD44vcJexkuXuQhH8BXQ3luXKgxQ5O4uRod7O+3f/6bcz7z50gCh8p28MslRz3cG14hoFX4OgRXFRs5U0yIEfuyXlvE34IYmVhz3mFaGStyNWS6pHqXVuyVlMt0KmLx+l87jyA+9URXahSr3elu86IBJkT8elQr5E1VeIuBeLMhVzcr47MaaT/91K8R7svlFYc2ZFG7WTF2MXSMaCpkCsXcrS5x/X9zSJnQzqAB26TGEG20egOBpWH4XSpb5skuYRVCv0Uvm3ukzOJE2QIRZjPFbuAra5lkJSrqzeHZy7jcOpbwtbuhlWlFWLNm0pOv9bzq12+RW72ModgRh5kvTFXUyPPUtwJm1NW7H8vKTlnsM0bUN0FH14GRLWo5Dxvggj+18ZDGnKIsUv0Hglu8+qrnvuLPP2VxG9ZKjlAkPi2x16CksmRN0GYFzxgzwx15nH944OU6vqMuhZkcSEzhUXOyJjhLla34pxOrmPYWUeO6mP7ZJnk3x1RyvsDQcrT+eyKFTnUG57+2XIpFxPHgAFBZs2lrAbqVrIQD3X/LAE5SKaPXqh5eJnb25MYVC3Ze+SdpIMgznwq3XtkTZCrk4NftRXw54JA6d4jY4LgJN2FGKpvexPZtSiFqxAM+ueZpGfw5ju2bZR2a3cKbxAktiUynL+0Nx+7VJAlQXBIaM+6EorBmaADgpigVUDbkt6b66gzT4I04hgPpnTUP96mq3YvhNjba4t2txXvK1qVUqhhiAoIYm9HRfZsyTMkDlVHOV9kBEGKNHO/i+bzfRW/68r2HASPpfwbiumIvadJPTyDBzHVPNpbIZAqYUAQK3WjkysCG4RhnMfkSRC8JnS138X7L/7JO80VZkkQFI/T1D7TZmvvIug09tZylgQRqIvF1PTNxdoMxeiD+QhuPfIkCOpiuVkF094xPEumBBECLwqZWrknsZ4r6CuvEq7iSsYEwXUTT7bIepjQIVi2BFHfTczpswOsrZSJcFbfi5yRPV+CIA9hYrbLi+Ez/MqYICoPQZi1vHnGmzHEWUrWBEGYFc9Yl5i5J4SaK9T7+bwJgjBrCTtdbI4+IVdVH0MRYnsxmRMENXoXs16LidZvSx6pHnvg1l+jbyrxikgcxThVz54gqjL51cmLlxb6Q5cFENhMqNvni7eSqI5FiOI8iFow7mYtYOmWU/RV5EMe9lmK1nYrwIO0y6yp+XmMWr0upmLWV3mGKbxDnFeYSaffuhCCKDeCg0N9s3BruekV1Md3utCJKnG3ZILttoqudzkEUYvFuYgPm9EaIyUvsWtBRREEoZaWbTs38nmS7SyM4wCFEaQ9Ubq9en1w7Igbuo8goIghae+joOXfbYRSSHkEwa6Wti0NzylUp6lifF0l+LDXzrWF9tywSIK0OaMQn/pv8HnGNIvhph8nUS1I1qKRdQnVFoslSJuPUPP58vXhRRYWHXAROeUUpjAVTJB2E69WnzmGJ9ltNjnmFrpEKZwgIMmYoWzcgco0twBBdBHojoOK9CTDKu7tAZ6UK8G4iJuRSj01hgcZAJlT4j58K9H+BCjjV58waHco1H/DFTrwZJsshgFBttWQyTlJmzdU+99ZWFnCQoAgo8pTlxvlWeof4cHXotyZCYJMYph+XoJPOYMg7gjMjpDuVXmEWbPKnW0ADzILUdq7XAiztBQ8HUfgg/EmAKYXdnVvM+jcZJVo+4wAPIiNNUh5QfLxcwovFBFm2SgYBHFDre2djjdBmGWvbngQe+yeevK/9Igwy17JIIg9dls9+Z6dIMyyVzIIYo/deE+m+QnCLDtFgyB2uM304pefvP96fyQrcRNkuRkPCoIEVS4foiDMslM0CGKHm2EvHkRBmGWottLqYpnD47tHXKIgzDLXJzyIOWYeenREqZqHL0seNiLMMlcdCGKOmcceVLclORc8lUeYZaY+EMQMr3Ct1fZwJe5CV1lBmGWmQhDEDK8FWofNUxBmmakQBDHDa8HWffhFX3y/bESYpa9GEEQfq4gt/d73Qpilr0oQRB8rBi39vG5EmKWvShBEHysmLf3kKAiz9NQJgujhxKyVO0kQZumpFATRw4llK5dCdwiz9FQKgujhxLaVC0kQZs2rFQSZx4h9C1uSIMyaVy0IMo9REi1sSIIwa161IMg8Rsm0sCEJwqzd6gVBkjF/HUHNd7dQ0AEE0bGsjNqYkQRhFgiSkfHrLsWswgrCrGlcEWLp2lxy7fRJgirwIEhy5u1HYL27W9juBUH82FuSo8yTBHkICJKkafsTep4kyEPG0UYO4s8KmY9E9dXJi5dTQmK7FwRhbsALiLfjA6UIsyYJ8u93fBJ4AeNkMsWu03aEWdtKoprefQNBmNjuQmJMb/+CIGMEub6/EVIcLaQdTMMCgfGkHechW8ohcUvv/vpxLog+sNAbhFgQgd+TdpyHbMGvapXhV2NBm+Q2lZQXV28Oz3qxkKhvKkjla4RfDW5Wu7A8WyTBV4+f8SeSZ4RfjYUNkuV0XeIu9uQKn4x+VtDVyQGR+r/YvWBptRAqJgJPnrUlCPKQmJrA3BwRUOGVKiTeEgRhFkcVQaaYCFDz8FJ9u6UlCMKsmKrA3OwQGFzJWRMEl9XYqQkCRUKgD6/U9M8E+frPSlZ/3OBeViStYFo2CKjdq16Y9f9oc5HrHx+wzcdGTxAkAgLblzk3CQIvEkElmJITAkPvsRFi9ULCi3BSF2RZEoFh7jEaYmFHa0l1YC5WCEw8JtsIsdZepA219r+zWgCEAQIBEaBGHI99C3KUIEjYA2oCQ7NDYIocoznIUHpcQWGnSwjkG4Ed7/RnCdJeQdnbP8eLQ99awXgsEJghxyxB2lALW78sdAkhfCOwuwzSzl2sbVFAEt/KwXhxEdAjh5YH2djZQrgVV6+Y3R0BjbBqOMnkLtaYJMqTNNX+6a9On9wlxQhAYGEEDMlh5EGwu7WwMjGdVwRsPk9nTZB18o6Qy6sSMVgIBPS/kzI2u1GINTZAd1ai6mrJVYjlYUwgYIeA2afopuZwJkjvTbrcBESxUyZ6+UPADzF6ebwQZLjTJfb2jqSgUxwu+lM5RtJBwC8xghBkuIz1jheJI5BFR8FoY45AR4qqefiiCiyY95/v4dWDTE2nyCLE/qotTNaIV6KilZD0lLMgd5lXU8ktqDN8krVoZC2J6qoRd2M3b0Og9H+cyhMalsJEBAAAAABJRU5ErkJggg==
> 若有的话，请列出来。

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/1ed01d380309cca4800350f4c1b19d8a26ac7d19
