### ISSUE TITLE
XArr 系列软件图标请求收录

### ISSUE THREAD

**Issue by xiaoyi510** [xushier/HD-Icons#12]
![image](https://user-images.githubusercontent.com/20254874/197980824-671cd71e-ff60-49e4-8819-753cfbbe4c8b.png)
项目地址: [https://xarr.52nyg.com](https://xarr.52nyg.com)

**Comment by xushier** [comment]
好的

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/929dd2221dc556a0806b4049147b5d960604a62e
