### ISSUE TITLE
Thunderbird

### ISSUE THREAD

**Issue by 631894570** [xushier/HD-Icons#121]
## 你想要新增什么图标？
Thunderbird
> 你想要新增什么图标？填写图标项目的完整名字。
Thunderbird
## 该图标有可参考的项目或 LOGO 地址吗？
![Thunderbird](https://github.com/xushier/HD-Icons/assets/43724996/7c9fd4d1-f367-4a0c-a86f-88f848fbce94)
https://hub.docker.com/r/ich777/thunderbird  一个docker组建的webmail客户端
> 若有的话，请列出来。

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
