### ISSUE TITLE
请求新增一枚clash verge 新款图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#123]
## 你想要新增什么图标？
clash verge 新款图标

## 该图标有可参考的项目或 LOGO 地址吗？

![287171682-eeac9916-f57e-4eaf-96dd-f4ea029a8389](https://github.com/xushier/HD-Icons/assets/52785574/84ed94ac-da87-41b8-871c-9a162fdba6e8)

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
