### ISSUE TITLE
请求添加Acunetix Web Vulnerability Scanner（AWVS）

### ISSUE THREAD

**Issue by BilikoX** [xushier/HD-Icons#132]
## 你想要新增什么图标？
Acunetix Web Vulnerability Scanner（AWVS）
https://www.acunetix.com/
## 该图标有可参考的项目或 LOGO 地址吗？
![1710286718129](https://github.com/xushier/HD-Icons/assets/15882517/ea42d858-8cc7-4573-88aa-dd0e1c7ff235)
![1659749279595](https://github.com/xushier/HD-Icons/assets/15882517/251e1b19-9ccd-4461-a22b-a795add395ad)

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
