### ISSUE TITLE
请求新增雷池圆角矩形图标

### ISSUE THREAD

**Issue by BackspaceM** [xushier/HD-Icons#134]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
请求新增雷池圆角矩形图标
## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
https://raw.githubusercontent.com/chaitin/SafeLine/main/documents/static/images/403.svg

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
