### ISSUE TITLE
抖音图标

### ISSUE THREAD

**Issue by ljk4160** [xushier/HD-Icons#135]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
抖音图标
## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
douyin.com

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
