### ISSUE TITLE
请求新增 linkding 图标

### ISSUE THREAD

**Issue by ocleo1** [xushier/HD-Icons#137]
## 你想要新增什么图标？

linkding 图标

## 该图标有可参考的项目或 LOGO 地址吗？

项目地址：https://github.com/sissbruecker/linkding

LOGO 地址：

![](https://raw.githubusercontent.com/sissbruecker/linkding/master/docs/header.svg)

**Comment by xushier** [comment]
这个好像是有的吧

**Comment by xushier** [comment]
哦，看错了，LinkAce跟他很像

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/9273165e221aada428c3d3ff5139cc9eef867460
