### ISSUE TITLE
请求添加tabby

### ISSUE THREAD

**Issue by guitarzsr** [xushier/HD-Icons#139]
## 你想要新增什么图标？
tabby-web，一个多平台SSH客户端的配置同步容器，参见https://tabby.sh/

## 该图标有可参考的项目或 LOGO 地址吗？
https://tabby.sh/32bf32ff6c87e8d18932.svg

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/a3cf74909df0e9167ca341a3e09caa802f6997b9
