### ISSUE TITLE
xiaoya docker 图标

### ISSUE THREAD

**Issue by jasonminwu** [xushier/HD-Icons#140]
希望新增 xiaoya docker 图标
项目地址：https://hub.docker.com/r/xiaoyaliu/alist
图标示例：https://s2.loli.net/2023/04/24/Z9bMjB3TutzKDGY.png

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/a3cf74909df0e9167ca341a3e09caa802f6997b9
