### ISSUE TITLE
请求增加飞牛OS的图标

### ISSUE THREAD

**Issue by jian263994241** [xushier/HD-Icons#142]
## 你想要新增什么图标？

 fnOS 飞牛OS的图标

> 你想要新增什么图标？填写图标项目的完整名字。

## 该图标有可参考的项目或 LOGO 地址吗？

https://www.fnnas.com/

> 若有的话，请列出来。

**Comment by xushier** [comment]
已经有了

**Comment by ChishFoxcat** [comment]
> ## 你想要新增什么图标？
> fnOS 飞牛OS的图标
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://www.fnnas.com/
> 
> > 若有的话，请列出来。

下载后才知道完整的文件名 
链接：https://github.com/xushier/HD-Icons/blob/main/border-radius/%E9%A3%9E%E7%89%9B%E7%A7%81%E6%9C%89%E4%BA%91_A.png

建议名称更改为 `fnOS` 更容易找到
