### ISSUE TITLE
飞牛fnOS

### ISSUE THREAD

**Issue by Kado814** [xushier/HD-Icons#143]
## 你想要新增什么图标？

> 飞牛nas

## 该图标有可参考的项目或 LOGO 地址吗？

> [fnOS-ICON](https://trim-helper.oss-rg-china-mainland.aliyuncs.com/images/Margin-1.png)

**Comment by xushier** [comment]
看看记录，都有了呀

**Comment by Kado814** [comment]
![image](https://github.com/user-attachments/assets/f9a74c16-5313-4a8f-8064-a07de369206d)
名称乱码

**Comment by xushier** [comment]
下载下来也乱码？
