### ISSUE TITLE
请求添加新图标(数据湖)

### ISSUE THREAD

**Issue by lutinglt** [xushier/HD-Icons#149]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。

Apache Iceberg, Lakekeeper

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

https://github.com/apache/iceberg
https://github.com/lakekeeper/lakekeeper

https://github.com/apache/iceberg/blob/main/site/docs/assets/images/iceberg-logo-icon.png
https://github.com/lakekeeper/lakekeeper/blob/main/ui/catalog/src/assets/bear.png

**Comment by lutinglt** [comment]
lakekeeper UI迁移了
新 logo 地址: https://github.com/lakekeeper/lakekeeper/blob/ct/ui/ui/catalog/src/assets/bear.png

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/7f28cf8f25cc235892dcedef73a5499450560069

**Comment by lutinglt** [comment]
感谢, 辛苦~
