### ISSUE TITLE
ChineseSubFinder 图标请求收录

### ISSUE THREAD

**Issue by tyzzz** [xushier/HD-Icons#15]
项目地址:
 https://github.com/allanpk716/ChineseSubFinder
 https://hub.docker.com/repository/docker/allanpk716/chinesesubfinder

**Comment by xushier** [comment]
> 项目地址: https://github.com/allanpk716/ChineseSubFinder https://hub.docker.com/repository/docker/allanpk716/chinesesubfinder

已添加
https://cdn.jsdelivr.net/gh/xushier/HD-Icons@master/border-radius/Chinesesubfinder_A.png
