### ISSUE TITLE
请求添加Linkace Searxng图标

### ISSUE THREAD

**Issue by ZevaXu** [xushier/HD-Icons#16]
Linkace是一个自部署的书签、链接管理系统。项目地址：https://github.com/Kovah/LinkAce

Searxng是一个自部署的搜索引擎。项目地址：https://github.com/searxng/searxng

**Comment by ZevaXu** [comment]
不好意思，看到linkace的了

**Comment by xushier** [comment]
> 不好意思，看到linkace的了

已添加
https://cdn.jsdelivr.net/gh/xushier/HD-Icons/border-radius/Searxng_A.png
https://cdn.jsdelivr.net/gh/xushier/HD-Icons/border-radius/Searx_A.png
