### ISSUE TITLE
可以做一个phpmyadmin的图标吗~

### ISSUE THREAD

**Issue by ukiyoec** [xushier/HD-Icons#18]
## 你想要新增什么图标？
**—— phpmyadmin 圆角图标**

## 该图标有可参考的项目或 LOGO 地址吗？
—— [phpmyadmin
](https://teddysun.com/wp-content/uploads/2013/09/phpMyAdmin.png)

**Comment by xushier** [comment]
有的
https://raw.githubusercontent.com/xushier/HD-Icons/master/border-radius/Pma_A.png
https://raw.githubusercontent.com/xushier/HD-Icons/master/border-radius/Pma_B.png
