### ISSUE TITLE
求帮忙绘制 Halo 博客图标

### ISSUE THREAD

**Issue by jdjxk** [xushier/HD-Icons#2]
地址如下，感谢！
https://halo.run/
https://halo.run/upload/2021/03/Adaptive256-463ca9b92e2d40268431018c07735842.png

**Comment by xushier** [comment]
好


| |
段松博
|
|
***@***.***
|
在2022年6月18日 ***@***.***> 写道：

地址如下，感谢！
https://halo.run/
https://halo.run/upload/2021/03/Adaptive256-463ca9b92e2d40268431018c07735842.png

**Comment by xushier** [comment]
要跟这个链接的一模一样？

**Comment by jdjxk** [comment]
不用，看您自己发挥

**Comment by xushier** [comment]
我也只是P一下，不会AI，谈不上绘制。。。。。

**Comment by jdjxk** [comment]
只需要图标形状尺寸统一就好了

**Comment by xushier** [comment]
嗯

**Comment by jdjxk** [comment]
miniflux 有时间的话也麻烦弄一下可以吗？
https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/miniflux.png

**Comment by xushier** [comment]
已更

**Comment by jdjxk** [comment]
辛苦了，非常感谢！
