### ISSUE TITLE
求cookiecloud图标

### ISSUE THREAD

**Issue by yangruiqq** [xushier/HD-Icons#23]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
cookiecloud
## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
https://github.com/easychen/CookieCloud

**Comment by xushier** [comment]
已添加

**Comment by yangruiqq** [comment]
> 

感谢
