### ISSUE TITLE
求帮忙制作flexget和nastools图标

### ISSUE THREAD

**Issue by jdjxk** [xushier/HD-Icons#3]
项目及示例如下，请自由发挥，感谢！

[flexget](https://www.flexget.com)
https://raw.githubusercontent.com/alexiri/helmcharts/master/flexget/Flexget-Logo.png

[nastools](https://github.com/jxxghp/nas-tools)
https://github.com/shuosiw/unraid/raw/master/images/nastools-icon.png

**Comment by xushier** [comment]
已加
