### ISSUE TITLE
JINKENS、SVN、GUACAMOLE这几个图标作者也可以支持一下哦

### ISSUE THREAD

**Issue by tangqijiang** [xushier/HD-Icons#31]
![image](https://user-images.githubusercontent.com/16813557/232227350-75d46030-74cb-48e0-94ac-caa53f091a18.png)
![image](https://user-images.githubusercontent.com/16813557/232227416-e2651a56-8cb5-4e8d-a03e-b4158b5f4de0.png)
![image](https://user-images.githubusercontent.com/16813557/232227496-b0bde1f4-83ab-4079-a47f-c786585b70fb.png)

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/a199e614a9201b787ad24f8cc1678f7ba69571c7
