### ISSUE TITLE
请求添加azure图标作为E5续订容器图标使用

### ISSUE THREAD

**Issue by lauren12133** [xushier/HD-Icons#32]
## 你想要新增什么图标？

请求添加azure图标作为E5续订容器图标使用

> 你想要新增什么图标？填写图标项目的完整名字。

E5 RE

## 该图标有可参考的项目或 LOGO 地址吗？

https://arunpotti.files.wordpress.com/2021/12/microsoft_azure.svg_.png

> 若有的话，请列出来。

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/7abd8b6b44be51caf7e2e8c12032b23d512a7d5e
