### ISSUE TITLE
增加新图标请求

### ISSUE THREAD

**Issue by x2287711259** [xushier/HD-Icons#34]
## 你想要新增什么图标？

1.nps内网穿透
2.melody音乐精灵

## 该图标有可参考的项目或 LOGO 地址吗？

1.https://ehang-io.github.io/nps/#/
2.https://github.com/foamzou/melody

**Comment by xushier** [comment]
melody那个logo是认真的嘛。。

**Comment by x2287711259** [comment]
我觉得还挺好看的

**Comment by xushier** [comment]
![Melody_A](https://user-images.githubusercontent.com/31540107/232764448-170388ee-be76-4ab4-9cfa-47fb7e8aca1e.png)

**Comment by x2287711259** [comment]
谢谢，这张怎么这么大，超过1M了

**Comment by x2287711259** [comment]
好谢谢，看到上传的了
