### ISSUE TITLE
routeros 图标

### ISSUE THREAD

**Issue by rastyu** [xushier/HD-Icons#36]
## 你想要新增什么图标？

> routeros 图标

## 该图标有可参考的项目或 LOGO 地址吗？
[routeros官方地址](https://mikrotik.com/software)
![routeros](https://user-images.githubusercontent.com/48859414/233244230-6d056717-1a30-442e-9c97-5540183914cd.png)

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/e670e41768ee78664964e7c7d7f74beb1035c8d1
