### ISSUE TITLE
请求增加谷歌云

### ISSUE THREAD

**Issue by x2287711259** [xushier/HD-Icons#39]
## 你想要新增什么图标？

谷歌云

## 该图标有可参考的项目或 LOGO 地址吗？

https://cloud.google.com/?hl=zh-cn

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 谷歌云
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://cloud.google.com/?hl=zh-cn

已添加 https://github.com/xushier/HD-Icons/commit/789e2d5dc3952ac9691609f09285db504ff718c3
