### ISSUE TITLE
请求grafana图标

### ISSUE THREAD

**Issue by Amadeus331** [xushier/HD-Icons#40]
## 你想要新增什么图标？
grafana
> 你想要新增什么图标？填写图标项目的完整名字。
[grafana docker](https://hub.docker.com/r/grafana/grafana/)
[grafana官网](https://grafana.com/)
## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
![图片](https://user-images.githubusercontent.com/15882517/234489128-f527ff8f-8905-4172-a37a-e5ccd36522d7.png)

[unraid icon](https://github.com/atribe/unRAID-docker/raw/master/icons/grafana.png)
[svg](https://grafana.com/media/images/logos/grafana-logo-footer.svg)

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/5d091afb8d9dd2efd77b557c9cbcaa1b00c7c625
