### ISSUE TITLE
请求新增图标

### ISSUE THREAD

**Issue by Amadeus331** [xushier/HD-Icons#45]
## 你想要新增什么图标？
B站录播姬

B站录播姬 | BiliBili Stream Recorder | 哔哩哔哩直播录制
## 该图标有可参考的项目或 LOGO 地址吗？
https://github.com/BililiveRecorder/BililiveRecorder
[svg logo](https://raw.githubusercontent.com/BililiveRecorder/BililiveRecorder/dev/.github/assets/logo.svg)

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/4c767f6181c4dda7d4fa6d871db90f63b21260d8
