### ISSUE TITLE
请求新增图标

### ISSUE THREAD

**Issue by Amadeus331** [xushier/HD-Icons#46]
## 你想要新增什么图标？
E5SubBot

## 该图标有可参考的项目或 LOGO 地址吗？
https://github.com/iyear/E5SubBot/
https://raw.githubusercontent.com/iyear/E5SubBot/master/pics/office.png

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> E5SubBot
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://github.com/iyear/E5SubBot/ https://raw.githubusercontent.com/iyear/E5SubBot/master/pics/office.png

这个更新好之后就命名为 Office 了

**Comment by xushier** [comment]
https://github.com/xushier/HD-Icons/commit/4c767f6181c4dda7d4fa6d871db90f63b21260d8
