### ISSUE TITLE
请求添加opencd图标

### ISSUE THREAD

**Issue by phui-chen** [xushier/HD-Icons#47]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
opencd
## 该图标有可参考的项目或 LOGO 地址吗？
![logo_waifu2x_noise2_scale2x](https://github.com/xushier/HD-Icons/assets/61391171/ade1e5bd-0c4e-4486-8854-379433e44a94)

> 若有的话，请列出来。

**Comment by xushier** [comment]
网站的话那可太多了，没必要做
