### ISSUE TITLE
MACOS

### ISSUE THREAD

**Issue by andy094** [xushier/HD-Icons#48]
## 你想要新增什么图标？
苹果虚拟机
> 你想要新增什么图标？填写图标项目的完整名字。
MACOS
## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 苹果虚拟机
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > MACOS
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。

已添加 https://github.com/xushier/HD-Icons/commit/ad9ea4501057522c62acddede31f47b0f9f2918c
