### ISSUE TITLE
图标需求3个，感谢作者

### ISSUE THREAD

**Issue by meii11** [xushier/HD-Icons#49]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
1. 兮克交换机
2. 华硕路由器
3. gitea
## 该图标有可参考的项目或 LOGO 地址吗？
1. https://img.meii.cc:50524/i/2023/06/10/64841a1c5ec3b.png
2. https://img.meii.cc:50524/i/2023/06/10/6484158a0ec8a.png
3. https://img.meii.cc:50524/i/2023/06/10/648410d11b452.png
> 若有的话，请列出来。
感谢作者大大！

**Comment by xushier** [comment]
收到

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> 1. 兮克交换机
> 2. 华硕路由器
> 3. gitea
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> 1. https://img.meii.cc:50524/i/2023/06/10/64841a1c5ec3b.png
> 2. https://img.meii.cc:50524/i/2023/06/10/6484158a0ec8a.png
> 3. https://img.meii.cc:50524/i/2023/06/10/648410d11b452.png
> 
> > 若有的话，请列出来。
> > 感谢作者大大！

已添加 https://github.com/xushier/HD-Icons/commit/297067279376c3a21eb8c0343dabdaf4d44d649b

**Comment by meii11** [comment]
感谢！！
