### ISSUE TITLE
CookieCloud

### ISSUE THREAD

**Issue by andy094** [xushier/HD-Icons#54]
## 你想要新增什么图标？
CookieCloud
> 你想要新增什么图标？填写图标项目的完整名字。
CookieCloud
## 该图标有可参考的项目或 LOGO 地址吗？
https://github.com/easychen/CookieCloud
> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> CookieCloud
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > CookieCloud
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://github.com/easychen/CookieCloud
> 
> > 若有的话，请列出来。

cookiecloud 本来就有的

**Comment by andy094** [comment]
抱歉，昨天看了一圈没看到
















在 2023-07-12 09:49:55，"小迪同学" ***@***.***> 写道：

Closed #54 as completed.
