### ISSUE TITLE
极空间NAS图标

### ISSUE THREAD

**Issue by hxp0521** [xushier/HD-Icons#56]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。

已添加 https://github.com/xushier/HD-Icons/commit/9ac0c23cffff9a2abdb9123ac989aef980ac7fec
