### ISSUE TITLE
iStoreOS图标加一下

### ISSUE THREAD

**Issue by hxp0521** [xushier/HD-Icons#57]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。

## 该图标有可参考的项目或 LOGO 地址吗？
/
> 若有的话，请列出来。
![argon](https://github.com/xushier/HD-Icons/assets/138567770/be50f4fe-0eec-41b9-b96f-112299a342ca)

**Comment by xushier** [comment]
istoreos也不是这个图啊

**Comment by hxp0521** [comment]
我直接复制的 登陆页的图标

**Comment by hxp0521** [comment]
直接用作openwrt的图标也行啊

**Comment by hxp0521** [comment]
![image](https://github.com/xushier/HD-Icons/assets/138567770/bad0f534-56ca-4ec3-86db-405ef1ce2e4b)
我直接用浏览器把他提取出来的

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/00af93d0cf09388449a4bc5ebf8039804cbeafb8
