### ISSUE TITLE
请求添加图标webos

### ISSUE THREAD

**Issue by flyingnight** [xushier/HD-Icons#61]
请求添加图标：腾飞Webos

官网地址：https://os.tenfell.cn/
问题反馈社区地址：https://txc.qq.com/products/464670/

**Comment by xushier** [comment]
> 请求添加图标：腾飞Webos
> 
> 官网地址：https://os.tenfell.cn/ 问题反馈社区地址：https://txc.qq.com/products/464670/

已添加 https://github.com/xushier/HD-Icons/commit/2494eb38217bf02e617d1d7070b19f3a2d5395db
