### ISSUE TITLE
flatnotes

### ISSUE THREAD

**Issue by rastyu** [xushier/HD-Icons#63]
## 你想要新增什么图标？

![android-chrome-512x512](https://github.com/xushier/HD-Icons/assets/48859414/a6d6db45-5dc7-4497-b1d0-0d123236529a)

## 该图标有可参考的项目或 LOGO 地址吗？

1. [flatnotes项目地址](https://github.com/dullage/flatnotes)

2. 还有个问题README页面 Freshrss显示有问题

![freshrss](https://github.com/xushier/HD-Icons/assets/48859414/01938c8f-e211-42f3-ada9-3b048e953875)

**Comment by xushier** [comment]
freshrss 文件没问题，不显示是由于 windows 不区分大小写造成的文件命名错误

**Comment by xushier** [comment]
已添加 https://github.com/xushier/HD-Icons/commit/a552abeb9236f0f4333c666123b8fc45113faa4e
