### ISSUE TITLE
AutoBangumi 图标申请

### ISSUE THREAD

**Issue by HUSTHKX** [xushier/HD-Icons#64]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。

AutoBangumi

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

https://github.com/EstrellaXD/Auto_Bangumi

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> AutoBangumi
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。
> 
> https://github.com/EstrellaXD/Auto_Bangumi

已添加 https://github.com/xushier/HD-Icons/commit/b6f2812c1dd1c688f23cea6324a3a18cb016dd86
