### ISSUE TITLE
请求更新unraid中adminer应用图标

### ISSUE THREAD

**Issue by HadokenM** [xushier/HD-Icons#65]
请求新增图标名字：
unrand应用admine
参考图标链接：
https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/adminer.png

**Comment by xushier** [comment]
> 请求新增图标名字： unrand应用admine 参考图标链接： https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/adminer.png

已经有了的 https://github.com/xushier/HD-Icons/blob/main/border-radius/Adminer_A.png

**Comment by HadokenM** [comment]
尴尬，不好意思，图标换了样，又没认真看。
