### ISSUE TITLE
求一个lucky项目的图标

### ISSUE THREAD

**Issue by LmanTs** [xushier/HD-Icons#69]
## 你想要新增什么图标？
迪佬，鄙人不才想求个高清的lucky图标
> 你想要新增什么图标？填写图标项目的完整名字。
这个是GitHub的项目地址(https://github.com/gdy666/lucky)
## 该图标有可参考的项目或 LOGO 地址吗？
项目官网可以参考到logo
> 若有的话，请列出来。
在官网的左上角有一个图标

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 迪佬，鄙人不才想求个高清的lucky图标
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > 这个是GitHub的项目地址(https://github.com/gdy666/lucky)
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> 项目官网可以参考到logo
> 
> > 若有的话，请列出来。
> > 在官网的左上角有一个图标

已添加 https://github.com/xushier/HD-Icons/commit/ecfc262505998f457c3b31ebe01c337f68c697f3

这个图标做得花了小半天时间。。。。。
