### ISSUE TITLE
可以制作智能家居类的docker容器图标吗

### ISSUE THREAD

**Issue by JKnuts** [xushier/HD-Icons#7]
大爱大佬的图标，做的非常好看
目前我自己在用的智能家居相关的docker容器
有【home assistant】【Zigbee2MQTT】【NODE-RED】【Tasmota】
大佬如感兴趣，请考虑一下

**Comment by xushier** [comment]
好的

**Comment by xushier** [comment]
> 大爱大佬的图标，做的非常好看 目前我自己在用的智能家居相关的docker容器 有【home assistant】【Zigbee2MQTT】【NODE-RED】【Tasmota】 大佬如感兴趣，请考虑一下

已更新

**Comment by JKnuts** [comment]
> > 大爱大佬的图标，做的非常好看 目前我自己在用的智能家居相关的docker容器 有【home assistant】【Zigbee2MQTT】【NODE-RED】【Tasmota】 大佬如感兴趣，请考虑一下
> 
> 已更新

谢谢大佬，还有个问题
我用了【nastools】的图标感觉比其他图标小一圈，不知道是不是边距不一样
