### ISSUE TITLE
请求新图标：Kubespider

### ISSUE THREAD

**Issue by tediorelee** [xushier/HD-Icons#70]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
Kubespider

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
https://github.com/opennaslab/kubespider
https://kubespider.netlify.app/
官网有现成logo

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> > Kubespider
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。
> > https://github.com/opennaslab/kubespider
> > https://kubespider.netlify.app/
> > 官网有现成logo

仔细看
![image](https://github.com/xushier/HD-Icons/assets/31540107/3933654b-d1e8-4e73-b84d-78b62259d19f)

**Comment by tediorelee** [comment]
> > ## 你想要新增什么图标？
> > > 你想要新增什么图标？填写图标项目的完整名字。
> > > Kubespider
> > 
> > 
> > ## 该图标有可参考的项目或 LOGO 地址吗？
> > > 若有的话，请列出来。
> > > https://github.com/opennaslab/kubespider
> > > https://kubespider.netlify.app/
> > > 官网有现成logo
> 
> 仔细看 ![image](https://user-images.githubusercontent.com/31540107/268478908-3933654b-d1e8-4e73-b84d-78b62259d19f.png)

我瞎了（
感谢~
