### ISSUE TITLE
新图标请求：overleaf, bookstack

### ISSUE THREAD

**Issue by GaugeAndGravity** [xushier/HD-Icons#71]
## 你想要新增什么图标？

- Overleaf
- Bookstack

## 该图标有可参考的项目或 LOGO 地址吗？

- Overleaf:
  - 单图标: 找到一个 https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/overleaf.png
  - logo: https://github.com/overleaf/overleaf/blob/main/doc/logo.png
- Bookstack:
  - https://github.com/BookStackApp/BookStack/blob/development/public/icon.png 但其实他们自己的页面用的都是蓝底白图的版本（）

感谢大佬

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> * Overleaf
> * Bookstack
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> * Overleaf:
>   
>   * 单图标: 找到一个 https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/overleaf.png
>   * logo: https://github.com/overleaf/overleaf/blob/main/doc/logo.png
> * Bookstack:
>   
>   * https://github.com/BookStackApp/BookStack/blob/development/public/icon.png 但其实他们自己的页面用的都是蓝底白图的版本（）
> 
> 感谢大佬

已添加 https://github.com/xushier/HD-Icons/commit/bb60ccc438226cf1d4749cbb17fe4707c1073e02
