### ISSUE TITLE
请增加Rocky Linux图标

### ISSUE THREAD

**Issue by dondongc** [xushier/HD-Icons#72]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。Rocky Linux

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。https://rockylinux.org/zh_CN/

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。Rocky Linux
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。https://rockylinux.org/zh_CN/

已添加 https://github.com/xushier/HD-Icons/commit/14417db141ff536b83193d4cec53dd111434e15a

**Comment by dondongc** [comment]
感谢回复，但发现rocky linux配色和原图logo不一致，浅绿色部分应为白色



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月6日(周五) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xushier/HD-Icons] 请增加Rocky Linux图标 (Issue #72)




 
Closed #72 as completed.

**Comment by xushier** [comment]
> 感谢回复，但发现rocky linux配色和原图logo不一致，浅绿色部分应为白色
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月6日(周五) 上午9:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xushier/HD-Icons] 请增加Rocky Linux图标 (Issue #72) Closed #72 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

主要是在图标这样一个小范围内，白色太多会显得太亮。

**Comment by xushier** [comment]
> 感谢回复，但发现rocky linux配色和原图logo不一致，浅绿色部分应为白色
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月6日(周五) 上午9:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xushier/HD-Icons] 请增加Rocky Linux图标 (Issue #72) Closed #72 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

后面再加两个白的吧

**Comment by xushier** [comment]
> 圆形的logo应该好做
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月12日(周四) 下午5:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xushier/HD-Icons] 请增加Rocky Linux图标 (Issue #72) 感谢回复，但发现rocky linux配色和原图logo不一致，浅绿色部分应为白色 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年10月6日(周五) 上午9:27 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xushier/HD-Icons] 请增加Rocky Linux图标 (Issue #72) Closed #72 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 主要是在图标这样一个小范围内，白色太多会显得太亮。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

圆的有一个了，不过也是浅绿色
