### ISSUE TITLE
想要一个微信读书的logo

### ISSUE THREAD

**Issue by Qigaoo** [xushier/HD-Icons#73]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。

已添加 https://github.com/xushier/HD-Icons/commit/1ad66e5e3094aa4570b3fb3877327037182435c9
