### ISSUE TITLE
请求一个英伟达图标

### ISSUE THREAD

**Issue by andy094** [xushier/HD-Icons#74]
## 你想要新增什么图标？
英伟达图标
> 你想要新增什么图标？填写图标项目的完整名字。
nvidia图标
## 该图标有可参考的项目或 LOGO 地址吗？
https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage/
> 若有的话，请列出来。
老哥求个高清图标，搜了一大圈没搜到合适的，跪谢

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 英伟达图标
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > nvidia图标
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage/
> 
> > 若有的话，请列出来。
> > 老哥求个高清图标，搜了一大圈没搜到合适的，跪谢

已添加 https://github.com/xushier/HD-Icons/commit/f1d3f561a47046983891ad1a3bef0553272ecac5
