### ISSUE TITLE
请求增加“哪吒监控”项目图标，谢谢！

### ISSUE THREAD

**Issue by cheny95** [xushier/HD-Icons#75]
## 你想要新增什么图标？

> 哪吒监控  NeZha

## 该图标有可参考的项目或 LOGO 地址吗？

> 
https://github.com/naiba/nezha
https://nezha.wiki/
![image](https://github.com/xushier/HD-Icons/assets/6293952/0eec4593-530c-4ea1-92c2-af5699072131)
![image](https://github.com/xushier/HD-Icons/assets/6293952/b18d7435-f2fa-4938-9f27-1bea45c7180f)

感谢您的工作。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 哪吒监控  NeZha
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 
> 
> https://github.com/naiba/nezha https://nezha.wiki/ ![image](https://user-images.githubusercontent.com/6293952/278194895-0eec4593-530c-4ea1-92c2-af5699072131.png) ![image](https://user-images.githubusercontent.com/6293952/278194927-b18d7435-f2fa-4938-9f27-1bea45c7180f.png)
> 
> 感谢您的工作。

已添加 https://github.com/xushier/HD-Icons/commit/330caa65f0df5f7179d8a664d20cb8d4b68091b6
