### ISSUE TITLE
请求增加Snapdrop图标

### ISSUE THREAD

**Issue by ChenXu178** [xushier/HD-Icons#77]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。
Snapdrop

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。
https://github.com/RobinLinus/snapdrop
https://github.com/RobinLinus/snapdrop/blob/master/client/images/logo_blue_512x512.png

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> > Snapdrop
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。
> > https://github.com/RobinLinus/snapdrop
> > https://github.com/RobinLinus/snapdrop/blob/master/client/images/logo_blue_512x512.png

已添加 https://github.com/xushier/HD-Icons/commit/39257f382217ad7b936d87b3f433cff47781f259
