### ISSUE TITLE
请求增加新图标

### ISSUE THREAD

**Issue by BackspaceM** [xushier/HD-Icons#78]
## 你想要新增什么图标？

>圆角矩形
 DELL、Moviepilog、威联通、ROG

## 该图标有可参考的项目或 LOGO 地址吗？
https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md

>  DELL-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dell.png
Moviepilog-https://raw.githubusercontent.com/jxxghp/MoviePilot-Frontend/main/public/logo.png
威联通1-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qnap-alt.png
威联通2-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qnap.png
ROG-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/asus-rog.png

感谢大佬的支持

**Comment by xushier** [comment]
moviepilot已经添加过了

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 圆角矩形
> > DELL、Moviepilog、威联通、ROG
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md
> 
> > DELL-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dell.png
> > Moviepilog-https://raw.githubusercontent.com/jxxghp/MoviePilot-Frontend/main/public/logo.png
> > 威联通1-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qnap-alt.png
> > 威联通2-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qnap.png
> > ROG-https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/asus-rog.png
> 
> 感谢大佬的支持

已添加 https://github.com/xushier/HD-Icons/commit/39257f382217ad7b936d87b3f433cff47781f259
