### ISSUE TITLE
请求新增music-tag-web图标

### ISSUE THREAD

**Issue by RenMu-V** [xushier/HD-Icons#79]
## 你想要新增什么图标？
music-tag-web
> 你想要新增什么图标？填写图标项目的完整名字。
https://github.com/xhongc/music-tag-web

## 该图标有可参考的项目或 LOGO 地址吗？
https://github.com/xhongc/music-tag-web

> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> music-tag-web
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > https://github.com/xhongc/music-tag-web
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://github.com/xhongc/music-tag-web
> 
> > 若有的话，请列出来。

已添加 https://github.com/xushier/HD-Icons/commit/39257f382217ad7b936d87b3f433cff47781f259

**Comment by xhongc** [comment]
hi
