### ISSUE TITLE
请求添加 CouchDB 的图标

### ISSUE THREAD

**Issue by GoodbyeNJN** [xushier/HD-Icons#80]
## 你想要新增什么图标？

> CouchDB
> 项目主页：https://couchdb.apache.org

## 该图标有可参考的项目或 LOGO 地址吗？

> https://couchdb.apache.org/image/logo@2x.png
> https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Apache_CouchDB_logo.svg/290px-Apache_CouchDB_logo.svg.png

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > CouchDB
> > 项目主页：https://couchdb.apache.org
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > https://couchdb.apache.org/image/logo@2x.png
> > https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Apache_CouchDB_logo.svg/290px-Apache_CouchDB_logo.svg.png

已添加 https://github.com/xushier/HD-Icons/commit/983a364a21975a46cd05cacf1551d5972f3accd0

**Comment by GoodbyeNJN** [comment]
非常感谢！
