### ISSUE TITLE
请求新增图标

### ISSUE THREAD

**Issue by xd88dx** [xushier/HD-Icons#81]
## 你想要新增什么图标？
Gitlab

> 你想要新增什么图标？填写图标项目的完整名字。
Gitlab

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> Gitlab
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > Gitlab
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。

已添加 https://github.com/xushier/HD-Icons/commit/983a364a21975a46cd05cacf1551d5972f3accd0
