### ISSUE TITLE
请求添加fail2ban图标

### ISSUE THREAD

**Issue by xd88dx** [xushier/HD-Icons#83]
## 你想要新增什么图标？
fail2ban
> 你想要新增什么图标？填写图标项目的完整名字。
https://github.com/orgs/linuxserver/packages/container/package/fail2ban
## 该图标有可参考的项目或 LOGO 地址吗？
https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/fail2ban-logo.png
> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> fail2ban
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > https://github.com/orgs/linuxserver/packages/container/package/fail2ban
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/fail2ban-logo.png
> 
> > 若有的话，请列出来。

已添加 https://github.com/xushier/HD-Icons/commit/b6b04e202e32486927a4a002c6d0728287f040a7
