### ISSUE TITLE
请求制作个115网盘图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#85]
## 你想要新增什么图标？
115网盘
> 你想要新增什么图标？填写图标项目的完整名字。
115网盘
## 该图标有可参考的项目或 LOGO 地址吗？
https://pc.115.com/
> 若有的话，请列出来。
![R](https://github.com/xushier/HD-Icons/assets/52785574/ac506861-6ac4-4e22-9ac7-bc67e9e2a64f)
![093230-608b5e2ed5912](https://github.com/xushier/HD-Icons/assets/52785574/e653584a-e2f4-45c7-bf20-df5f05264272)
![OIP](https://github.com/xushier/HD-Icons/assets/52785574/fe3a002b-8137-4a71-b035-8149b7121352)

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 115网盘
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> > 115网盘
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://pc.115.com/
> 
> > 若有的话，请列出来。
> > ![R](https://private-user-images.githubusercontent.com/52785574/290134779-ac506861-6ac4-4e22-9ac7-bc67e9e2a64f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjA4NjksIm5iZiI6MTcwMjU2MDU2OSwicGF0aCI6Ii81Mjc4NTU3NC8yOTAxMzQ3NzktYWM1MDY4NjEtNmFjNC00ZTIyLTlhYzctYmM2N2U5ZTJhNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzMjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOWY4NDFlNjllM2EwMzBkM2MxMzJkNWMyNDJiY2Y3YzE0NjZmMzZjYWYyZTQ4N2E0NTYwMTQyMjY3MWQwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aYCEz1ewSp0a4CEZ4cTdIG2KvKW9z6mi3mVxk273kbI)
> > ![093230-608b5e2ed5912](https://private-user-images.githubusercontent.com/52785574/290134807-e653584a-e2f4-45c7-bf20-df5f05264272.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjA4NjksIm5iZiI6MTcwMjU2MDU2OSwicGF0aCI6Ii81Mjc4NTU3NC8yOTAxMzQ4MDctZTY1MzU4NGEtZTJmNC00NWM3LWJmMjAtZGY1ZjA1MjY0MjcyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzMjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNjFkYjhmZmFlMTY1MTM0MzllZjQyZTE5OTRjNjNlOGE1ZmEwYWQ4ODI0NGNiNWY5NzVlODgwY2Y0NWZiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8MYUn3nBdC5vxRstLUhXXzjMx4beOIAFb0CMVbE9_KQ)
> > ![OIP](https://private-user-images.githubusercontent.com/52785574/290134855-fe3a002b-8137-4a71-b035-8149b7121352.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjA4NjksIm5iZiI6MTcwMjU2MDU2OSwicGF0aCI6Ii81Mjc4NTU3NC8yOTAxMzQ4NTUtZmUzYTAwMmItODEzNy00YTcxLWIwMzUtODE0OWI3MTIxMzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzMjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZTQ1M2U1Y2QwY2Y5M2Q3ZmI0MmIzOGFlODdhNDlkNjEyOTQzOTA1NmU1N2I2YTBiZTE3MmY5ZWZiZTAxZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ppdTab_W3_24tWyusznfL6DO7ML_kckj1zD-2ToJ4hg)

已添加 https://github.com/xushier/HD-Icons/commit/a1b633e3b252c57d9668358467392793a3e45a84
