### ISSUE TITLE
新增图片

### ISSUE THREAD

**Issue by 596142041** [xushier/HD-Icons#86]
## 你想要新增什么图标？
禅道

## 该图标有可参考的项目或 LOGO 地址吗？
https://www.zentao.net/
希望添加禅道的LOGO，LOGO上面建议写上禅道

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 禅道
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://www.zentao.net/ 希望添加禅道的LOGO，LOGO上面建议写上禅道

已添加 https://github.com/xushier/HD-Icons/commit/0623b6ed623ceaca221bca47bf559088cd617683
