### ISSUE TITLE
添加MQTT服务器：EMQX图标

### ISSUE THREAD

**Issue by 596142041** [xushier/HD-Icons#87]
## 你想要新增什么图标？

EMQX图标

## 该图标有可参考的项目或 LOGO 地址吗？

https://www.emqx.io/，网页里面的LOGO

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> EMQX图标
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> [https://www.emqx.io/，网页里面的LOGO](https://www.emqx.io/%EF%BC%8C%E7%BD%91%E9%A1%B5%E9%87%8C%E9%9D%A2%E7%9A%84LOGO)

已添加 https://github.com/xushier/HD-Icons/commit/34d7c283f12024ed4535615f36e1578ca302a48e
