### ISSUE TITLE
New Icon Request 

### ISSUE THREAD

**Issue by labdiynez** [xushier/HD-Icons#89]
1. unbound
2. qbitmanage
3. wifi-card
4. diskspeed
5. gitea-runner
[https://raw.githubusercontent.com/kutzilla/unraid-templates/master/images/unbound.png](url)
![image](https://github.com/xushier/HD-Icons/assets/52117480/379ae81e-624f-42c7-94f7-669c311c3a16)
[https://hotio.dev/webhook-avatars/qbitmanage.png](url)
![image](https://github.com/xushier/HD-Icons/assets/52117480/acaf0a2b-7d72-42d0-8018-958dc7756e9d)
[https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/wifi-card.png](url)
![image](https://github.com/xushier/HD-Icons/assets/52117480/21c4117b-9b28-4091-8846-a10bdc55b9dd)
[https://raw.githubusercontent.com/jbartlett777/DiskSpeed/master/DiskSpeed.png](url)
![image](https://github.com/xushier/HD-Icons/assets/52117480/1f42f167-fbaf-44f3-8bf0-a9a12ae3a6c3)
[https://avatars.githubusercontent.com/u/54465427?v=4](url)
![image](https://github.com/xushier/HD-Icons/assets/52117480/5a77619b-8436-4a02-8cf9-8b1a800b884a)

**Comment by xushier** [comment]
> 1. unbound
> 2. qbitmanage
> 3. wifi-card
> 4. diskspeed
> 5. gitea-runner
>    [https://raw.githubusercontent.com/kutzilla/unraid-templates/master/images/unbound.png](url)
>    ![image](https://private-user-images.githubusercontent.com/52117480/294401948-379ae81e-624f-42c7-94f7-669c311c3a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzIxMTIsIm5iZiI6MTcwNDUzMTgxMiwicGF0aCI6Ii81MjExNzQ4MC8yOTQ0MDE5NDgtMzc5YWU4MWUtNjI0Zi00MmM3LTk0ZjctNjY5YzMxMWMzYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjk0N2I1ZGViN2Q2NTVjOWY1NWRkNGU1MDU3ZmJjNDExOTdiOTI2NTliYmMwMGI3ZTBkMTllYmZkY2Q4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oo_U2Hre5qqufpH5JybWByQXBVU1QLe-Iwm_SqDE1AE)
>    [https://hotio.dev/webhook-avatars/qbitmanage.png](url)
>    ![image](https://private-user-images.githubusercontent.com/52117480/294401989-acaf0a2b-7d72-42d0-8018-958dc7756e9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzIxMTIsIm5iZiI6MTcwNDUzMTgxMiwicGF0aCI6Ii81MjExNzQ4MC8yOTQ0MDE5ODktYWNhZjBhMmItN2Q3Mi00MmQwLTgwMTgtOTU4ZGM3NzU2ZTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MzMwMGRjMThmYzdkYTA4MWMyMzc1MjVmMjBmNjE3MTdjNGI3MzFmM2U4MTkzNTRjN2I3NGQ4NzMyZTNhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXSyS3sFQahQnFe3IDCeF3xN9R5fibFy5-oyFycWfIE)
>    [https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/wifi-card.png](url)
>    ![image](https://private-user-images.githubusercontent.com/52117480/294402031-21c4117b-9b28-4091-8846-a10bdc55b9dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzIxMTIsIm5iZiI6MTcwNDUzMTgxMiwicGF0aCI6Ii81MjExNzQ4MC8yOTQ0MDIwMzEtMjFjNDExN2ItOWIyOC00MDkxLTg4NDYtYTEwYmRjNTViOWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGM5MWUzMmMwZGVkMzNkZDY4OTY4OTVkYjFlMmMzODc5YTM3NjIwN2NhNGJhNTFhOWQ0YzY2MmQxNTc0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aUAr3i8NbGIc0wbbKe6drqMGA74NPaYXkr08xmILISA)
>    [https://raw.githubusercontent.com/jbartlett777/DiskSpeed/master/DiskSpeed.png](url)
>    ![image](https://private-user-images.githubusercontent.com/52117480/294402249-1f42f167-fbaf-44f3-8bf0-a9a12ae3a6c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzIxMTIsIm5iZiI6MTcwNDUzMTgxMiwicGF0aCI6Ii81MjExNzQ4MC8yOTQ0MDIyNDktMWY0MmYxNjctZmJhZi00NGYzLThiZjAtYTlhMTJhZTNhNmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNTU4YjQ5MWVjZWM1NDY3YjZiMDU3ODQ5ZDQ0NWE4MGU1NjRmYzEzNzAwY2U0ODYyYmNhNGQ5NWVmZDVhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z8YFHVMVXR6I0AjXx9aaIPlv5SjVAHGL7Fr7e7hxGVA)
>    [https://avatars.githubusercontent.com/u/54465427?v=4](url)
>    ![image](https://private-user-images.githubusercontent.com/52117480/294402598-5a77619b-8436-4a02-8cf9-8b1a800b884a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzIxMTIsIm5iZiI6MTcwNDUzMTgxMiwicGF0aCI6Ii81MjExNzQ4MC8yOTQ0MDI1OTgtNWE3NzYxOWItODQzNi00YTAyLThjZjktOGIxYTgwMGI4ODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMzI5N2U1Zjk5NzllZDNkYWRhNDQ5MzVkZmFiYmJhZjM5YWEwZTVlYWVkOGY4NTM0YTQ0MjlmNzhmZTAwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OU38snlRXdSzhHyFDVIPk0ssCtVhUkIAdHK3JsikCeA)

前两个已添加 https://github.com/xushier/HD-Icons/commit/2f26097f4ea4ed39610dffad0593cb9e428f4edd

**Comment by labdiynez** [comment]
6. plex meta manager
[https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/docs/_static/favicon.png](url)
7. radarr
[https://radarr.video/](url)
8. homer
[https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/icons/logo.svg](url)

**Comment by xushier** [comment]
> 6. plex meta manager
>    [https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/docs/_static/favicon.png](url)
> 7. radarr
>    [https://radarr.video/](url)
> 8. homer
>    [https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/icons/logo.svg](url)

https://github.com/xushier/HD-Icons/commit/de1870e744bc9947c05edb79e6d88181225c5b50

**Comment by labdiynez** [comment]
> > 6. plex meta manager
> >    [https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/docs/_static/favicon.png](url)
> > 7. radarr
> >    [https://radarr.video/](url)
> > 8. homer
> >    [https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/icons/logo.svg](url)
> 
> [de1870e](https://github.com/xushier/HD-Icons/commit/de1870e744bc9947c05edb79e6d88181225c5b50)

Thank you very much, beautiful icons
