### ISSUE TITLE
请求图标授权，用于 CasaOS 第三方应用商店

### ISSUE THREAD

**Issue by Cp0204** [xushier/HD-Icons#90]
你好，我是 [quark_auto_save](https://github.com/Cp0204/quark_auto_save) 作者，同时也在维护着 [CasaOS-AppStore-Play](https://github.com/Cp0204/CasaOS-AppStore-Play)（CasaOS 第三方应用商店）。

CasaOS-AppStore-Play 中应用图标是我添加应用时随手找的，圆角圆形参差不齐，偶然发现本项目，发现新大陆！

能否使用本项目的图标替换商店源的部分应用图标？会在 README 加入本项目链接，感谢！

**Comment by xushier** [comment]
> 你好，我是 [quark_auto_save](https://github.com/Cp0204/quark_auto_save) 作者，同时也在维护着 [CasaOS-AppStore-Play](https://github.com/Cp0204/CasaOS-AppStore-Play)（CasaOS 第三方应用商店）。
> 
> CasaOS-AppStore-Play 中应用图标是我添加应用时随手找的，圆角圆形参差不齐，偶然发现本项目，发现新大陆！
> 
> 能否使用本项目的图标替换商店源的部分应用图标？会在 README 加入本项目链接，感谢！

额，昨天刚看到夸克网盘自动保存这个项目。。。。。

**Comment by Cp0204** [comment]
> 额，昨天刚看到夸克网盘自动保存这个项目。。。。。

是的，就是从Star找过来的😉
