### ISSUE TITLE
求更新图标: 幻兽帕鲁Palworld

### ISSUE THREAD

**Issue by tediorelee** [xushier/HD-Icons#91]
## 你想要新增什么图标？

幻兽帕鲁Palworld

> 你想要新增什么图标？填写图标项目的完整名字。

Palworld

## 该图标有可参考的项目或 LOGO 地址吗？

https://img.game8.co/3820250/bfd9f77c798fbb2cd6a3dee41cb54924.png/show

> 若有的话，请列出来。

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> 幻兽帕鲁Palworld
> 
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> Palworld
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://img.game8.co/3820250/bfd9f77c798fbb2cd6a3dee41cb54924.png/show
> 
> > 若有的话，请列出来。

已添加  https://github.com/xushier/HD-Icons/commit/fc57f7d51d0b1353ce0061adaa998e23ed8d0979
