### ISSUE TITLE
新增一枚MT Photos 图标新样式

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#92]
## 你想要新增什么图标？
MT Photos
小迪老师能否新增一枚MT Photos 图标新样式
## 该图标有可参考的项目或 LOGO 地址吗？

![MTphoto](https://github.com/xushier/HD-Icons/assets/52785574/51480e64-dd32-435e-83a4-699dc3d09854)

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> MT Photos 小迪老师能否新增一枚MT Photos 图标新样式
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> ![MTphoto](https://private-user-images.githubusercontent.com/52785574/299640070-51480e64-dd32-435e-83a4-699dc3d09854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDIzNDUsIm5iZiI6MTcwNjU0MjA0NSwicGF0aCI6Ii81Mjc4NTU3NC8yOTk2NDAwNzAtNTE0ODBlNjQtZGQzMi00MzVlLTgzYTQtNjk5ZGMzZDA5ODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MjcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZjRlYWU5Y2JkZGE5MDQ4OGM3NWI5OTc1ZjBkNTA1NWU1ZmE5ODM3NDMxOTA2ODQ4N2E5OGE2OWMxNjUyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rO8VhwI6Y9EoHYtLapH4zLfsdz7GnwZIq4MH-8HJMUI)

已添加  https://github.com/xushier/HD-Icons/commit/fc57f7d51d0b1353ce0061adaa998e23ed8d0979
