### ISSUE TITLE
请求新增Nginx Proxy Manager图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#93]
## 你想要新增什么图标？

Nginx Proxy Manager

## 该图标有可参考的项目或 LOGO 地址吗？

![Nginxproxymanager](https://github.com/xushier/HD-Icons/assets/52785574/05ac6fb0-ab2d-4586-9633-b1d8f9e7d7b7)

![nginx-proxy-manager](https://github.com/xushier/HD-Icons/assets/52785574/42bb1928-70c7-4448-b5e9-9de82f34c84b)

![nginx-proxy-manager-icon](https://github.com/xushier/HD-Icons/assets/52785574/05e6596a-3570-4654-9075-e97d0283e4f8)

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> Nginx Proxy Manager
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> ![Nginxproxymanager](https://private-user-images.githubusercontent.com/52785574/300175982-05ac6fb0-ab2d-4586-9633-b1d8f9e7d7b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjY1MzksIm5iZiI6MTcwNjM2NjIzOSwicGF0aCI6Ii81Mjc4NTU3NC8zMDAxNzU5ODItMDVhYzZmYjAtYWIyZC00NTg2LTk2MzMtYjFkOGY5ZTdkN2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE0MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTBlOGQ5MDNjNGUxMjhkMjM5NjNjYjVlMTk3ZDc2OTRmZTBiYjBjOTg4MDdkYjdkNTQ3MDk2ZmQ4YWEzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.orBogaELVRF1dM7WIv4zkfuu_gSgDvlYVmgF31k7XZI)
> 
> ![nginx-proxy-manager](https://private-user-images.githubusercontent.com/52785574/300175985-42bb1928-70c7-4448-b5e9-9de82f34c84b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjY1MzksIm5iZiI6MTcwNjM2NjIzOSwicGF0aCI6Ii81Mjc4NTU3NC8zMDAxNzU5ODUtNDJiYjE5MjgtNzBjNy00NDQ4LWI1ZTktOWRlODJmMzRjODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE0MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5N2QxZjYwNGE2ZDQ4ZjM3ZWM0OWIxMTRiYWNlOGM0YzczZGM2ZTEwNDczOTQ2MTJiMzcwYTI5MDI4OTQwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iQxm6xZvkF_ztupkwuBEmdyAcV17ocbHAosMVDf4Pdw)
> 
> ![nginx-proxy-manager-icon](https://private-user-images.githubusercontent.com/52785574/300176039-05e6596a-3570-4654-9075-e97d0283e4f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjY1MzksIm5iZiI6MTcwNjM2NjIzOSwicGF0aCI6Ii81Mjc4NTU3NC8zMDAxNzYwMzktMDVlNjU5NmEtMzU3MC00NjU0LTkwNzUtZTk3ZDAyODNlNGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE0MzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZmY0MGJiNGQ4ZmYwMDkwZTI3YzlmOWU2ZDYyMzEzZGE5YTc2ZGQ1NTY1ZTRjYmZkZWRiY2YzZjhiYmQzODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tBU-TsQy0A2hFFt_xnsgy-YHVRVdEvUbBhZIAbzlhNM)

这几个是有的
