### ISSUE TITLE
求添加大数据和监控相关的图标

### ISSUE THREAD

**Issue by lutinglt** [xushier/HD-Icons#95]
## 你想要新增什么图标？

> airflow; doris; flink; hadoop; hive; impala; superset; cadvisor; datagrip; glances;
> airflow; doris; flink; hadoop; hive; impala; superset; 这几个是 Apache 大数据相关的项目
> cadvisor;  这个是容器监控, 常用来和 Prometheus 使用监控容器
> datagrip; 这个是 JerBrains 连接数据库的 IDE
> glances; 这个 Python 的系统监控
## 该图标有可参考的项目或 LOGO 地址吗？

> airflow (分布式DAG调度系统)
![airflow](https://github.com/xushier/HD-Icons/assets/131967983/742fc798-aedd-441c-acaa-5397f0e1051a)
> doris (分布式OLAP数据库)
![doris](https://github.com/xushier/HD-Icons/assets/131967983/49280246-fd8a-4456-9f1c-0936e6f91d32)
> flink (分布式流计算框架)
![flink](https://github.com/xushier/HD-Icons/assets/131967983/caccaada-cb92-4ce2-8988-fd8bb328a636)
> hadoop (分布式存储系统)
![hadoop](https://github.com/xushier/HD-Icons/assets/131967983/3e3c7171-290c-40aa-8dc8-455326ae2b77)
> hive (分布式数据仓库系统)
![hive](https://github.com/xushier/HD-Icons/assets/131967983/2bddc59b-5b1a-458b-8457-1d50871f49d9)
> impala (分布式即席查询框架)
![impala](https://github.com/xushier/HD-Icons/assets/131967983/464b4ab2-7378-4b17-b923-6e638e77d56d)
> superset (数据可视化)
![superset_Pic](https://github.com/xushier/HD-Icons/assets/131967983/c45c0e92-8b6f-4f0a-93c4-2427a84f0f2a)
> cadvisor (容器监控)
![cadvisor](https://github.com/xushier/HD-Icons/assets/131967983/a413f012-0d09-4725-bee8-7c1adec71896)
> datagrip (SQL客户端)
![datagrip](https://github.com/xushier/HD-Icons/assets/131967983/144a7674-daef-47f8-9664-cce986204b98)
> glances (系统监控)
![glances](https://github.com/xushier/HD-Icons/assets/131967983/423ce5e2-1d57-4dc6-ab55-c5c1440a240a)

**Comment by lutinglt** [comment]
hive 有一个高清的连接
https://[hive.apache.org/images/hive.svg](https://hive.apache.org/images/hive.svg)
superset 有另一个颜色的版本
https://[superset.apache.org/img/superset-mark-dark.svg](https://superset.apache.org/img/superset-mark-dark.svg)

**Comment by xushier** [comment]
嗯，昨天已经做好了

**Comment by lutinglt** [comment]
光速

**Comment by lutinglt** [comment]
可以再添加一个图标吗?
oauth2-proxy
项目地址: https://github.com/oauth2-proxy/oauth2-proxy
图标: https://oauth2-proxy.github.io/oauth2-proxy/img/logos/OAuth2_Proxy_icon.svg

**Comment by xushier** [comment]
> Reference in n

已添加 https://github.com/xushier/HD-Icons/commit/7efa62387b096b8b46543ee0318889fcf4941a09

**Comment by lutinglt** [comment]
😸 超赞, 辛苦了, 好像没有 glances , 然后 Flink 的松鼠的眼睛怎么了 🤣

**Comment by xushier** [comment]
> 😸 超赞, 辛苦了, 好像没有 glances , 然后 Flink 的松鼠的眼睛怎么了 🤣

Flink 已更新，Glances 已更新.

**Comment by lutinglt** [comment]
nicejob
