### ISSUE TITLE
请求 Sun-Panel 图标

### ISSUE THREAD

**Issue by sepshow** [xushier/HD-Icons#96]
## 你想要新增什么图标？

Sun-Panel

## 该图标有可参考的项目或 LOGO 地址吗？

![favicon (1)](https://github.com/xushier/HD-Icons/assets/52785574/e9c8f6e3-d2ff-48a2-9f09-9f95fa78562d)

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> Sun-Panel
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> ![favicon (1)](https://private-user-images.githubusercontent.com/52785574/301360814-e9c8f6e3-d2ff-48a2-9f09-9f95fa78562d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MzMyNzMsIm5iZiI6MTcwODUzMjk3MywicGF0aCI6Ii81Mjc4NTU3NC8zMDEzNjA4MTQtZTljOGY2ZTMtZDJmZi00OGEyLTlmMDktOWY5NWZhNzg1NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE2MjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1N2I5YmY2ODQ1ZGQzYWMwMDY1MzdlNTI0YmYxY2Q0ZDQ2OTE2OTAxNjQ4NTViNTY0MTE3ZDdiOTUxY2YzZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYbe7Bdy6Gg6AMJMdMRujf2clQlhTlFVASrDdQfdlmc)

已添加 https://github.com/xushier/HD-Icons/commit/357779264011d5bb8741ba90a90a1b53d1d96027
