### ISSUE TITLE
请求“九块记账”图标

### ISSUE THREAD

**Issue by xzxnc** [xushier/HD-Icons#97]
## 你想要新增什么图标？

> getmoneynote/moneynote-api
## 该图标有可参考的项目或 LOGO 地址吗？

> https://demo.moneywhere.com/logo.svg

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > getmoneynote/moneynote-api
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > https://demo.moneywhere.com/logo.svg

已添加 https://github.com/xushier/HD-Icons/commit/7efa62387b096b8b46543ee0318889fcf4941a09
