### ISSUE TITLE
请求添加Kopia图标

### ISSUE THREAD

**Issue by jdjxk** [xushier/HD-Icons#98]
## 你想要新增什么图标？

Kopia
增量备份软件

## 该图标有可参考的项目或 LOGO 地址吗？

https://raw.githubusercontent.com/kopia/kopia/master/icons/kopia.svg

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> Kopia 增量备份软件
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> https://raw.githubusercontent.com/kopia/kopia/master/icons/kopia.svg

已添加 https://github.com/xushier/HD-Icons/commit/7efa62387b096b8b46543ee0318889fcf4941a09
