### ISSUE TITLE
请求添加图标

### ISSUE THREAD

**Issue by pdone** [xushier/HD-Icons#99]
## 你想要新增什么图标？

> 你想要新增什么图标？填写图标项目的完整名字。

- 文心一言
- 通义千问
- https://ipw.cn
- https://itdog.cn
- https://dnschecker.org/

## 该图标有可参考的项目或 LOGO 地址吗？

> 若有的话，请列出来。

文心一言 
https://nlp-eb.cdn.bcebos.com/logo/favicon.ico

通义千问 
https://img.alicdn.com/imgextra/i4/O1CN01c26iB51UyR3MKMFvk_!!6000000002586-2-tps-124-122.png

ipw.cn
https://ipw.cn/logo.svg

itdog.cn
https://www.itdog.cn/favicon.ico

dnschecker.org
https://dnschecker.org/themes/common/images/general/logo.svg

### 当前效果

![image](https://github.com/xushier/HD-Icons/assets/34151215/68af8194-55ad-4b6a-86e8-c5bf68089db7)

**Comment by xushier** [comment]
> ## 你想要新增什么图标？
> > 你想要新增什么图标？填写图标项目的完整名字。
> 
> * 文心一言
> * 通义千问
> * https://ipw.cn
> * https://itdog.cn
> * https://dnschecker.org/
> 
> ## 该图标有可参考的项目或 LOGO 地址吗？
> > 若有的话，请列出来。
> 
> 文心一言 https://nlp-eb.cdn.bcebos.com/logo/favicon.ico
> 
> 通义千问 https://img.alicdn.com/imgextra/i4/O1CN01c26iB51UyR3MKMFvk_!!6000000002586-2-tps-124-122.png
> 
> ipw.cn https://ipw.cn/logo.svg
> 
> itdog.cn https://www.itdog.cn/favicon.ico
> 
> dnschecker.org https://dnschecker.org/themes/common/images/general/logo.svg
> 
> ### 当前效果
> ![image](https://private-user-images.githubusercontent.com/34151215/306472041-68af8194-55ad-4b6a-86e8-c5bf68089db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODI3MjIsIm5iZiI6MTcwOTQ4MjQyMiwicGF0aCI6Ii8zNDE1MTIxNS8zMDY0NzIwNDEtNjhhZjgxOTQtNTVhZC00YjZhLTg2ZTgtYzViZjY4MDg5ZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE2MTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNjRhYmE0OTFjYmVhNDZjZmNiOWY1NmU2YjFlMGNmNmFhYTViYjg4NTQ5ZmM5NTFjMWZiZWU2NWU2MGQ3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.66ipyo7QLXFbmuhwd2YTIZgPjNY2ZSWP6pTGNxEdRkg)

已添加 https://github.com/xushier/HD-Icons/commit/7efa62387b096b8b46543ee0318889fcf4941a09

**Comment by pdone** [comment]
thks!
